<!DOCTYPE html>
<html lang="en"><head>
<link href="../slides/_theme/iu-trident.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.40">

  <meta name="author" content="Professor Sarah Bauerle Danzman">
  <meta name="dcterms.date" content="2026-07-17">
  <title>INTL 503 — International Political Economy – The Politics of Multinational Corporations</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2c51baf0c2adc8025befded91fc35e78.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="iu-trident.png" data-background-position="2% 2%" data-background-size="15%" class="quarto-title-block center">
  <h1 class="title">The Politics of Multinational Corporations</h1>
  <p class="subtitle">INTL 503 | Chapter 9 — Group-Work Format</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor Sarah Bauerle Danzman 
</div>
</div>
</div>

  <p class="date">July 17, 2026</p>
</section>
<section id="todays-plan" class="slide level2">
<h2>Today’s Plan</h2>
<div class="callout callout-important no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Today’s Big Question</strong></p>
</div>
<div class="callout-content">
<p><span style="font-size: 1.4em; line-height: 1.4;"><strong>A multinational answers to many governments but to no global authority — so who actually controls it?</strong></span></p>
</div>
</div>
</div>
<div id="tbl-plan" class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="font-size: 22px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Section</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">What we'll cover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 48%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">1 · One Firm, Many Sovereigns</td>
<td style="text-align: left; width: 52%;">Why the firm and the state answer to different masters</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 48%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">2 · Group Work: How States and Firms Negotiate Control</td>
<td style="text-align: left; width: 52%;">Four groups each build one slide answering a core question from the chapter, then report back</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 48%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">3 · The Securitization of Investment</td>
<td style="text-align: left; width: 52%;">Screening, CFIUS, and today's reading and podcast</td>
</tr>
</tbody>
</table>


</div>
</div>
<aside class="notes">
<p>A brief orientation. It’s a Friday, so we open with Quiz 2 on Chapters 5 through 9, then run today’s session. Yesterday, Chapter 8, was the economics of the multinational — what it is, why firms produce abroad, who hosts them. Today, Chapter 9, is the politics: now that we understand why MNCs exist, we ask who governs them, and the answer turns out to be surprisingly fractured. I’ll lecture only the shared foundation — Vernon’s core tension between the global firm and the territorial state, dramatized by Chile’s 1971 copper nationalization. Once we have that shared vocabulary, you’ll move into four groups, each responsible for reconstructing one part of the chapter’s answer from the reading itself: how host countries have tried to control multinationals, how advanced economies do the same, why bargaining power shifts once an investment is sunk, and why the world never built a global rulebook for investment the way it did for trade. Each group builds one slide and reports back. Only after that do we turn to the emerging issue our reading and podcast are about — the securitization of investment and CFIUS — which I’ll set up and we’ll discuss, along with today’s student presentation on my own article. Hold the Big Question throughout: a multinational answers to many governments but to no single global authority — so who, in the end, actually controls it?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="one-firm-many-sovereigns" class="title-slide slide level1 center" data-background-color="#990000">
<h1>One Firm, Many Sovereigns</h1>

</section>
<section id="chile-1971-who-owns-the-copper" class="slide level2">
<h2>Chile, 1971: Who Owns the Copper?</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Chile’s economy ran on copper — and the biggest mines were owned by two U.S. multinationals, <strong>Anaconda</strong> and <strong>Kennecott</strong>.</p>
<ul>
<li>In <strong>1971</strong>, President Salvador Allende <strong>nationalized</strong> the mines — a unanimous vote of the Chilean Congress</li>
<li>Compensation was slashed for “excess profits”; the firms fought back, lobbied Washington, froze Chilean assets abroad</li>
<li>The MNC had become a <strong>flashpoint of sovereignty, foreign policy, and Cold War politics</strong></li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>A foreign firm owned a strategic national resource on Chilean soil. <strong>Whose rules apply — Chile’s, the home country’s, or the firm’s own global calculation?</strong></p>
<p>That collision is at the heart of the politics of the multinational corporation.</p>
</div>
</div>
</div>
<div style="text-align:center; margin-top:0.6em;">
<p><img data-src="images/allende.jpg" style="height:300px; width:auto; border:1px solid #ccc;"></p>
<p><span style="font-size:0.5em; color:#535054;">Salvador Allende, President of Chile (1970–1973)</span></p>
</div>
</div></div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Chapter 8 examined why firms invest abroad. Chapter 9 turns to what happens once they do — when a profit-seeking global firm operates inside a sovereign state with goals of its own.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Let me open where the politics is rawest. For most of the twentieth century, Chile’s economy was copper, and the largest copper mines were owned not by Chileans but by two American multinationals, Anaconda and Kennecott. Think about what that means: the commanding heights of a nation’s economy, its single most important export, owned and run by foreign firms answering to shareholders in New York. In 1971 the socialist government of Salvador Allende nationalized those mines — the Chilean Congress voted unanimously for it — and then, invoking a doctrine of “excess profits,” sharply reduced the compensation paid to the companies. The firms did not go quietly: they pursued legal claims, lobbied the U.S. government, helped freeze Chilean copper shipments and assets abroad, and the episode became entangled with U.S. covert action and the eventual coup against Allende in 1973. I open here because the case strips the chapter down to its essence. A foreign-owned firm controls a strategic asset physically located inside another country’s borders. So whose rules govern it? Chile’s, as the territorial sovereign? The United States’, as the home country protecting its firms? Or the firm’s own global profit calculation, which recognizes no single national master? That collision — between territorial sovereignty and a borderless firm — is the entire subject of today. Yesterday we asked why firms invest abroad. Today we ask what happens politically once they have, when a profit-seeking global enterprise sets up inside a sovereign state that has objectives of its own.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-core-tension-state-and-firm" class="slide level2">
<h2>The Core Tension: State and Firm</h2>
<div id="tbl-twologics" class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="font-size: 22px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">The State</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">The Multinational</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Frame of reference</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Territorial — one national jurisdiction</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Global — the worldwide operation</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Objective</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Maximize national welfare (jobs, revenue, security)</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Maximize firm/shareholder welfare across all markets</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Loyalty</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">To citizens who can vote and demand</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">To shareholders, not to any one host</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Time horizon</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Bound to the nation, indefinitely</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Mobile — can exit, relocate, restructure</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Vernon’s insight: <em>“the people in any national jurisdiction have a right to maximize their well-being… The MNC, on the other hand, is bent on maximizing the well-being of its stakeholders from global operations, without accepting responsibility for the consequences in individual jurisdictions.”</em> (Vernon 1998)</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>The host’s dilemma:</strong> it <em>needs</em> MNCs to capture FDI’s benefits, yet <em>cannot trust</em> them to deliver those benefits on their own. Almost all the politics of MNCs is governments managing this dilemma.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Raymond Vernon, the scholar who essentially founded the modern study of multinationals, framed the tension better than anyone, and this table is his diagnosis. The state and the firm operate on two logics that simply do not line up. The state’s frame of reference is territorial — one jurisdiction, bounded by borders. Its objective is to maximize the welfare of the people inside those borders: jobs, tax revenue, security, development. Its loyalty runs to citizens, who vote and organize and make demands. And it is stuck to the nation indefinitely; a government cannot relocate. The multinational’s frame of reference is the entire globe — it optimizes across all its markets at once. Its objective is to maximize returns to its shareholders, wherever they sit. Its loyalty is to those shareholders, not to any particular host country. And, crucially, it is mobile: it can exit, relocate production, restructure its corporate form to route around a rule it dislikes. Vernon’s own words, in the callout, are worth reading aloud: people in a national jurisdiction have a right to try to maximize their well-being within that jurisdiction, while the MNC is bent on maximizing its stakeholders’ well-being from global operations without accepting responsibility for the consequences in any individual jurisdiction. Out of that mismatch comes the host country’s fundamental dilemma, the bottom callout, and it’s the thread for the whole day: the host needs the multinational, because as we saw yesterday FDI brings capital, technology, and access the country can’t easily get otherwise — but it cannot simply trust the firm to deliver those benefits, because the firm is optimizing for itself, not for the host. Nearly everything governments do toward MNCs — regulating, bargaining, incentivizing, and now screening — is an attempt to manage that single dilemma. That dilemma is exactly what your four groups are about to reconstruct, each taking one part of the chapter’s answer: how host countries in the developing world have tried to control multinationals, how advanced economies regulate them, why bargaining power shifts once an investment is sunk, and why the world never built a global rulebook for investment the way it did for trade.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="group-work-how-states-and-firms-negotiate-control" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Group Work: How States and Firms Negotiate Control</h1>

</section>
<section id="group-work-instructions" class="slide level2">
<h2>Group Work Instructions</h2>
<div class="callout callout-important no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>The exercise</strong></p>
</div>
<div class="callout-content">
<p>Break into <strong>four groups.</strong> Each group gets <strong>10 minutes</strong> to read its assigned pages and build <strong>one slide</strong> that teaches its question as clearly and succinctly as possible, then <strong>5 minutes</strong> to report back to the class. Groups can raise their own questions, or ask clarifying questions, as part of the report-back.</p>
</div>
</div>
</div>
<div id="tbl-groupquestions" class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="font-size: 20px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Question</th>
<th data-quarto-table-cell-role="th" style="text-align: center; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Reading (Oatley Ch. 9)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 10%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Group 1</td>
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 68%;">How did developing countries try to control multinationals — and why did the 1960s–70s nationalization wave collapse?</td>
<td style="text-align: center; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 22%;">pp. 189–192</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 10%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Group 2</td>
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 68%;">How do advanced industrialized countries regulate multinationals, and why are sovereign wealth funds politically controversial?</td>
<td style="text-align: center; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 22%;">pp. 192–196</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 10%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Group 3</td>
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 68%;">Why does bargaining power shift between a firm and a host government over the life of an investment — and why do governments compete with locational incentives?</td>
<td style="text-align: center; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 22%;">pp. 196–201</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 10%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Group 4</td>
<td style="text-align: left; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 68%;">Why is there no "World Investment Organization" — and what did the world build instead?</td>
<td style="text-align: center; padding-top: 14px; padding-bottom: 14px; line-height: 1.35; width: 22%;">pp. 202–209</td>
</tr>
</tbody>
</table>


</div>
</div>
<aside class="notes">
<p>Each group’s question maps onto one contiguous, clearly-headed subsection of the chapter, so tell each group exactly which pages to open to — that’s the fastest way to get four groups reading in parallel instead of hunting through the whole chapter. Group 1 works from “Regulating Multinational Corporations in the Developing World” (performance requirements, the nationalization wave, export-processing zones). Group 2 works from “Regulating Multinational Corporations in the Advanced Industrialized Countries” (sector restrictions, the CNOOC/Dubai Ports/Lenovo cases, sovereign wealth funds). Group 3 works from “Bargaining with Multinational Corporations” (the bargaining-power logic, the obsolescing bargain, locational incentives). Group 4 works from “The International Regulation of Multinational Corporations” (the Calvo Doctrine, the UN Resolution on Permanent Sovereignty, TRIMs, the MAI’s collapse, BITs and ISDS) — this is both the longest reading and the concept I most want you to leave with, so Group 4 gets 10 minutes instead of 7. The reference slides that follow after these instructions give each group a chart or table to build from — Groups 1, 3, and 4 have solid reference material; Group 2 has the sovereign wealth fund chart but will need to pull the sector-restriction cases directly from the reading, since the book doesn’t tabulate those. As groups report back, listen for whether they reach for the reference material to make their point, and use it yourself to correct or extend what they present — and note for the class explicitly which of the ten chapter key terms each group just covered.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-the-host-countrys-toolkit" class="slide level2">
<h2>Reference: The Host Country’s Toolkit</h2>
<p>A <strong>performance requirement</strong> is a condition a host government attaches to FDI to make the firm’s behavior serve <strong>national</strong> objectives — not just the firm’s bottom line.</p>
<div id="tbl-performance" class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="font-size: 21px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Tool</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">What it forces the firm to do</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 30%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Local-content rules</td>
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 70%;">A set share of inputs must be sourced domestically — building local suppliers</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 30%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Export requirements</td>
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 70%;">The firm must export a set share of output — earning foreign exchange</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 30%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Technology transfer</td>
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 70%;">The firm must license or share technology with local partners</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 30%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Joint-venture / equity caps</td>
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 70%;">Foreign ownership is capped; a local partner must hold equity (control stays partly home)</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 30%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Employment &amp; training</td>
<td style="text-align: left; padding-top: 11px; padding-bottom: 11px; line-height: 1.3; width: 70%;">Mandated hiring, training, or management localization of host-country nationals</td>
</tr>
</tbody>
</table>


</div>
</div>
<aside class="notes">
<p>Reference table only — the performance-requirement toolkit (local-content rules, export requirements, technology transfer, JV/equity caps, employment &amp; training). Useful for Group 1. The aim is to capture the spillovers from Chapter 8: rather than let the MNC simply assemble and repatriate profits, these rules require linkages to local firms, workers, and technology. Several of these tools were later restricted by the WTO’s TRIMs agreement as trade-distorting — a link Group 4 may surface too.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-nationalization-and-export-processing-zones" class="slide level2">
<h2>Reference: Nationalization and Export-Processing Zones</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-expropriation" class="quarto-float quarto-figure quarto-figure-center" alt="Bar chart of the number of forced divestments (expropriation acts) of foreign firms per year, 1960 to 1985. Acts climb through the late 1960s, surge to a peak of about 83 in 1975 during the NIEO era, then collapse almost to zero by the early 1980s." width="88%">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-expropriation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="day08-chapter09-groupwork_files/figure-revealjs/fig-expropriation-1.png" id="fig-expropriation" style="width:88.0%" alt="Bar chart of the number of forced divestments (expropriation acts) of foreign firms per year, 1960 to 1985. Acts climb through the late 1960s, surge to a peak of about 83 in 1975 during the NIEO era, then collapse almost to zero by the early 1980s.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-expropriation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Export-processing zones (EPZs)</strong> — carved-out enclaves offering duty-free imports, tax breaks, streamlined rules, and (often) lighter labor regulation, in exchange for export-oriented jobs. Taiwan and South Korea used EPZs from the 1960s–70s to attract investment even while regulating it closely elsewhere; from a handful of zones in the 1970s to thousands worldwide today.</p>
<aside class="notes">
<p>Reference chart + EPZ definition. Useful for Group 1. The chart shows the nationalization wave (Fig. 9.1 in Oatley) rising through the NIEO era, peaking around 1975, then collapsing by the early 1980s as the debt crisis left developing countries needing capital and bargaining power began shifting back toward firms — the mechanism Group 3 will explain. EPZs are the other side of the developing-world story: even the most restrictive regulators, like Taiwan and South Korea, built EPZs specifically to attract the investment they wanted.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-sovereign-wealth-funds" class="slide level2">
<h2>Reference: Sovereign Wealth Funds</h2>
<p>A <strong>sovereign wealth fund (SWF)</strong> is a <strong>state-owned investment fund</strong> that invests national savings — often oil revenue or reserves — in assets abroad.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-swf" class="quarto-float quarto-figure quarto-figure-center" alt="Dual-axis chart, 2002 to 2024. A crimson area shows sovereign wealth fund assets under management rising from about 1 trillion dollars in 2002 to about 13.5 trillion in 2024. A navy dashed line shows SWF assets as a share of the world's inward FDI stock, rising from about 13 percent to roughly a quarter and then holding near 25 to 27 percent." width="78%">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-swf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="day08-chapter09-groupwork_files/figure-revealjs/fig-swf-1.png" id="fig-swf" style="width:78.0%" alt="Dual-axis chart, 2002 to 2024. A crimson area shows sovereign wealth fund assets under management rising from about 1 trillion dollars in 2002 to about 13.5 trillion in 2024. A navy dashed line shows SWF assets as a share of the world's inward FDI stock, rising from about 13 percent to roughly a quarter and then holding near 25 to 27 percent.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-swf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
<aside class="notes">
<p>Reference chart only. Useful for Group 2. SWFs collectively manage on the order of $13 trillion (2025); Norway’s fund alone holds about $1.8 trillion; the other major players are China, the Gulf states, and Singapore. This chart doesn’t cover why advanced economies restrict MNC ownership of sensitive sectors (Japan’s historical restrictions, the CNOOC-Unocal 2005 and Dubai Ports World 2006 blocked deals, Lenovo-IBM’s 2005 approval after scrutiny) — that’s in the reading (pp.&nbsp;192–196) and Group 2 should pull those cases directly from the text. When the investor is a foreign government rather than a private firm, hosts suspect political rather than commercial motives — that’s the hinge into the national-security screening we close on today.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-the-obsolescing-bargain" class="slide level2">
<h2>Reference: The Obsolescing Bargain</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-obsolescing" class="quarto-float quarto-figure quarto-figure-center" alt="A line chart of relative bargaining power over the life of an investment. Before the investment, the multinational's bargaining power is high and the host's is low. At the moment capital is committed and becomes a sunk, immovable asset, the lines cross: the host's power rises and the firm's falls as the project matures." width="86%">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-obsolescing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="day08-chapter09-groupwork_files/figure-revealjs/fig-obsolescing-1.png" id="fig-obsolescing" style="width:86.0%" alt="A line chart of relative bargaining power over the life of an investment. Before the investment, the multinational's bargaining power is high and the host's is low. At the moment capital is committed and becomes a sunk, immovable asset, the lines cross: the host's power rises and the firm's falls as the project matures.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-obsolescing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
<aside class="notes">
<p>Reference chart only. Useful for Group 3. Before investing, the firm can shop among eager hosts and win generous terms. After the capital is sunk into an immovable mine, plant, or pipeline, it can’t credibly threaten to leave, so the host can raise taxes, demand renegotiation, even expropriate — the original deal obsolesces (Moran 1974). This is the single most useful concept in the chapter: it explains both the expropriation wave Group 1 covers and why firms came to demand the treaty protections Group 4 covers. Bargaining power differs by sector — natural-resource investments are highly susceptible to this dynamic; low-skilled manufacturing, where capital is mobile and no host has a monopoly on cheap labor, is not, which is why MNCs retain more leverage there.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-locational-incentives" class="slide level2">
<h2>Reference: Locational Incentives</h2>
<p>Inducements a host offers to <strong>win</strong> an investment: <strong>tax holidays, subsidies, cash grants, cheap land, infrastructure, regulatory relief.</strong></p>
<p><em>Example — the U.S. South:</em> in 1990 the Deep South built <strong>no cars</strong>; today Alabama, Georgia, Mississippi, and South Carolina build <strong>2M+/year</strong>, lured by competing state incentive packages. BMW’s Spartanburg, SC plant (1992) started it — roughly $135M in incentives, about $67,500 per job. Alabama’s Mercedes package (mid-1990s) ran $253–300M, roughly $200,000–250,000 per job.</p>
<aside class="notes">
<p>Reference text only. Useful for Group 3. The growing size and frequency of these packages — across the OECD, from 285 programs totaling $11B in 1989 to 362 programs totaling $18B by 1993 — suggests host countries are at a disadvantage bargaining with MNCs over manufacturing investment specifically, the flip side of the obsolescing bargain: manufacturing capital is more mobile than natural-resource capital, so hosts compete rather than extract. Worth connecting explicitly to the obsolescing-bargain chart on the previous reference slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-asserting-sovereignty-the-right-to-nationalize" class="slide level2">
<h2>Reference: Asserting Sovereignty — The Right to Nationalize</h2>
<p>When performance requirements weren’t enough, developing host countries asserted a more radical claim in the 1960s–70s: the sovereign <strong>right to nationalize</strong> foreign firms.</p>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="the-calvo-doctrine">The Calvo Doctrine</h3>
<p>A foreign investor is entitled to <strong>no more than national treatment</strong>, and disputes must be settled in the <strong>host’s own courts under host law</strong> — <em>not</em> through the investor’s home government or international arbitration. Sovereignty, not special protection.</p>
</div><div class="column" style="width:50%;">
<h3 id="permanent-sovereignty-over-natural-resources">Permanent Sovereignty over Natural Resources</h3>
<p><strong>UN General Assembly Resolution 1803 (1962)</strong> affirmed every state’s right to control — and <strong>expropriate</strong> — foreign-owned resources in the national interest, with compensation set by the host. The economic charter of the <strong>NIEO</strong>.</p>
</div></div>
<aside class="notes">
<p>Reference text only. Useful for Group 4. Both doctrines assert the same principle: the territorial state is supreme over the foreign firm. This marks the peak of host-country power — and it is what the later BIT/ISDS treaty regime was designed to undo. The Calvo Doctrine, named for the nineteenth-century Argentine jurist Carlos Calvo, holds that a foreign investor may not appeal to their home government or international arbitration; the 1962 UN Resolution globalized that principle for natural resources specifically. Group 4 should connect this to where the chapter ends up: the BIT regime is essentially the negation of Calvo, since it lets firms bypass host courts entirely and sue states before international arbitrators.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-trade-has-the-wto-investment-has-3300-treaties" class="slide level2">
<h2>Reference: Trade Has the WTO; Investment Has 3,300 Treaties</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-iia" class="quarto-float quarto-figure quarto-figure-center" alt="Line chart of the cumulative number of international investment agreements (mostly bilateral investment treaties) from 1959 to 2024. The count is near zero until the late 1980s, explodes through the 1990s and 2000s to roughly 3,300, then plateaus and slightly declines after about 2017 as treaties are terminated." width="86%">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-iia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="day08-chapter09-groupwork_files/figure-revealjs/fig-iia-1.png" id="fig-iia" style="width:86.0%" alt="Line chart of the cumulative number of international investment agreements (mostly bilateral investment treaties) from 1959 to 2024. The count is near zero until the late 1980s, explodes through the 1990s and 2000s to roughly 3,300, then plateaus and slightly declines after about 2017 as treaties are terminated.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-iia-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4
</figcaption>
</figure>
</div>
</div>
</div>
<aside class="notes">
<p>Reference chart only. Useful for Group 4. A bilateral investment treaty (BIT) is a two-country pact protecting each other’s investors — national treatment, MFN, limits on expropriation, and investor-state dispute settlement (ISDS): the firm can sue the state before international arbitrators. Instead of one organization, the world built 3,300 of these, one at a time, because capital-exporting and capital-importing states could never agree in a multilateral venue. Group 4 has two more reference slides on this — the TRIMs/MAI failures and the home-vs-host conflict table — use whichever combination best supports their explanation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-trims-and-the-mai" class="slide level2">
<h2>Reference: TRIMs and the MAI</h2>
<p>Governments spent <strong>decades</strong> trying to build multilateral investment rules, with limited success.</p>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="trims-a-partial-measure">TRIMs — a partial measure</h3>
<p>The WTO’s <strong>Trade-Related Investment Measures</strong> agreement (1995) bans only the <strong>trade-distorting</strong> performance requirements — chiefly <strong>local-content</strong> and <strong>trade-balancing</strong> rules. It disciplines a few host tools but creates <strong>no general investment regime.</strong></p>
</div><div class="column" style="width:50%;">
<h3 id="mai-the-comprehensive-attempt">MAI — the comprehensive attempt</h3>
<p>The <strong>Multilateral Agreement on Investment</strong>, negotiated at the <strong>OECD (1995–1998)</strong>, aimed to be a comprehensive investment treaty — strong investor protections, binding ISDS. It <strong>collapsed in 1998</strong> amid NGO and public opposition over sovereignty, and disagreement among the negotiating governments themselves.</p>
</div></div>
<div class="columns">
<div class="column" style="width:34%;">
<div style="text-align:center; margin-top:0.6em;">
<p><img data-src="images/mai-cartoon.jpg" style="width:58.0%" alt="Editorial cartoon on the 1998 Multilateral Agreement on Investment negotiations."></p>
</div>
</div><div class="column" style="width:66%;">
<p>Earlier attempts also failed: the <strong>1948 Havana Charter</strong> (ITO) and the <strong>1970s UN Code of Conduct on TNCs.</strong> Across three venues — <strong>UN, GATT/WTO, OECD</strong> — and nearly 30 years of talks, no comprehensive framework emerged.</p>
</div></div>
<aside class="notes">
<p>Reference material only. Useful for Group 4. TRIMs came in with the WTO’s founding in 1995 and bans only local-content and trade-balancing rules — a trade agreement that clips a few investment-related wings, not a general regime. The MAI, negotiated among the rich countries at the OECD from 1995–1998, was meant to be the real thing — a comprehensive treaty with binding investor-state arbitration — and collapsed under a combination of NGO/public opposition and disagreement among OECD governments themselves (France ultimately walked away). Three venues, nearly three decades, no comprehensive multilateral framework.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="reference-why-no-wto-for-investment-home-vs.-host" class="slide level2">
<h2>Reference: Why No WTO for Investment? Home vs.&nbsp;Host</h2>
<div id="tbl-homehost" class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="font-size: 20px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;"></th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Home countries</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Host countries</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Who they are</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Capital-EXPORTERS — advanced, home to MNCs</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Capital-IMPORTERS — developing, host to MNCs</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">What they want rules to do</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">PROTECT investors; lock in access; restrain host interference</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">PRESERVE sovereignty; keep the right to regulate &amp; screen</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Their model doctrine</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Strong investor rights + ISDS (anti-Calvo)</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Calvo Doctrine + permanent sovereignty</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 22%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Whom rules should bind</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Discipline HOST STATES</td>
<td style="text-align: left; padding-top: 12px; padding-bottom: 12px; line-height: 1.35; width: 39%;">Discipline the FIRMS</td>
</tr>
</tbody>
</table>


</div>
</div>
<aside class="notes">
<p>Reference table only. Useful for Group 4. Rules that protect firms (what home countries want) are rules that constrain host sovereignty (what host countries refuse) — the same rule, read from two directions. With no overlap on whom to bind, the multilateral deal never closed, and the world defaulted to a decentralized, investor-protective BIT patchwork instead. Contrast the WTO (state-to-state; only states have standing; one organization) with the investment “non-regime” (investor-to-state ISDS; firms sue states; thousands of treaties, no organization) — that contrast is the direct answer to today’s Big Question.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="the-securitization-of-investment" class="title-slide slide level1 center" data-background-color="#990000">
<h1>The Securitization of Investment</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Emerging issue</span></p>
</div>
</section>
<section id="from-attracting-fdi-to-screening-it" class="slide level2">
<h2>From Attracting FDI to Screening It</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-screening" class="quarto-float quarto-figure quarto-figure-center" alt="Line chart of the cumulative number of economies with national-security FDI screening mechanisms, 1995 to 2024, rising slowly to about 10 by 2010, then accelerating sharply after the 2018 US FIRRMA reform and the 2020-21 COVID period to about 40." width="90%">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-screening-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="day08-chapter09-groupwork_files/figure-revealjs/fig-screening-1.png" id="fig-screening" style="width:90.0%" alt="Line chart of the cumulative number of economies with national-security FDI screening mechanisms, 1995 to 2024, rising slowly to about 10 by 2010, then accelerating sharply after the 2018 US FIRRMA reform and the 2020-21 COVID period to about 40.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-screening-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>The pattern reverses. For four decades, states <strong>competed to attract</strong> FDI; now advanced economies <strong>screen and sometimes block</strong> it on <strong>national-security</strong> grounds. In the U.S., <strong>CFIUS</strong> — strengthened by <strong>FIRRMA (2018)</strong> — reviews foreign deals; <strong>342 filings in 2023</strong> alone. “Economic security is national security.”</p>
<p><span style="font-size:0.82em; color:#535054;">🎧 <strong>Podcast:</strong> Skadden, <em>Economic Statecraft &amp; Foreign Investment Screening</em> — the screening “toolkit” in practice.</span></p>
</div>
</div>
</div>
<aside class="notes">
<p>And now the emerging issue we’ve been building toward, and notice it completes a full circle back to the beginning of the lecture and back to the four groups’ reports. For roughly forty years, the dominant story your groups just reconstructed was liberalization and competition to attract FDI — Group 3’s locational incentives, EPZs from Group 1’s reading, the BIT explosion Group 4 covered. The chart shows the counter-movement that has erupted in the last decade: the spread of national-security investment screening, creeping along at a low level through the 2000s, then bending sharply upward after 2018’s FIRRMA reform, which substantially expanded CFIUS, the Committee on Foreign Investment in the United States. CFIUS is busy — 342 filings in 2023 alone — and even investment from a close ally can now be blocked. The animating slogan, which you’ll hear in the Skadden podcast, is “economic security is national security.” Here’s the conceptual payoff: the developing host countries of the 1970s asserted sovereignty over foreign firms through the Calvo Doctrine and expropriation (Group 4’s reading); the advanced capital-exporters spent forty years dismantling that and building investor protections; and now those same advanced economies are reasserting exactly that host sovereignty — the right to regulate, screen, and block foreign investment — but rebranded from “economic nationalism” to “national security.” In effect, the Calvo impulse is returning in the world’s richest countries, now justified on security grounds. That’s our reading and today’s student presentation.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- The article-overview slide was removed: a student presents the Bauerle Danzman (2025) SPE article; the lecture hands off after "From Attracting FDI to Screening It." -->
</section>
<section id="recap-who-governs-the-multinational" class="slide level2">
<h2>Recap: Who Governs the Multinational?</h2>
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>Today’s Big Question —</strong> A multinational answers to many governments but to no global authority — so who actually controls it?</p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="from-control-to-competition">From control to competition</h3>
<ul>
<li><strong>One firm, many sovereigns:</strong> Vernon’s tension — global firm vs.&nbsp;territorial state</li>
<li><strong>Group 1:</strong> hosts push back — performance requirements, nationalization, then EPZs to attract investment</li>
<li><strong>Group 2:</strong> advanced economies regulate too — sector restrictions, sovereign wealth funds</li>
<li><strong>Group 3:</strong> the <strong>obsolescing bargain</strong> explains the swing — power shifts once capital is sunk, and firms compete for it via locational incentives</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="governance-or-its-absence">Governance, or its absence</h3>
<ul>
<li><strong>Group 4:</strong> no World Investment Organization — the <strong>Calvo Doctrine</strong>, <strong>TRIMs</strong>, the <strong>MAI</strong>’s collapse — home and host want opposite rules</li>
<li>So: <strong>3,300 BITs</strong> + <strong>ISDS</strong>, not one body</li>
<li><strong>Now:</strong> screening &amp; <strong>CFIUS</strong> rebuild host control as <em>national security</em> (securitized political economy)</li>
</ul>
</div></div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>The throughline: the multinational has long operated in the gap between a <strong>global economy</strong> and a <strong>world of sovereign states.</strong> No international organization filled that gap, and today the <strong>security state</strong> is moving into it.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Let’s pull the whole day together around the Big Question — what I lectured, and what your four groups just built and reported back. The left column traces host countries moving from controlling MNCs to competing for them, and it’s entirely your groups’ work: Group 1 traced how developing hosts pushed back with performance requirements and nationalization, then built EPZs to attract investment once the expropriation wave collapsed; Group 2 showed that even advanced economies regulate MNCs, especially through sovereign wealth fund scrutiny; Group 3 gave us the single most useful concept in the chapter, the obsolescing bargain, which explains why power swings the way it does and why hosts compete for mobile manufacturing investment with locational incentives. The right column is Group 4’s story, and it’s the one to remember: investment never got an organization the way trade got the WTO, because home and host countries wanted rules to do opposite things — protect firms versus preserve sovereignty — and could never agree whether to bind states or bind firms. So the world defaulted to a decentralized patchwork of 3,300 bilateral treaties with investor-state arbitration. And now the newest turn, which I lectured directly: the securitization of investment, screening regimes and CFIUS rebuilding host control over the foreign firm, but in the language of national security rather than economic nationalism. The throughline, the closing callout: the multinational corporation has always lived in the gap between a genuinely global economy and a world still organized into sovereign states. No international organization was ever built to fill that gap — and today it is the national-security state that is moving in to fill it. That’s the politics of the multinational corporation. Now let’s discuss.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="iu-trident.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>INTL 503 | The Politics of Multinational Corporations</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.15,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/Sarah-BD\.github\.io\/intl503\/");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>