<!DOCTYPE html>
<html lang="en"><head>
<link href="../slides/_theme/iu-trident.png" rel="icon" type="image/png">
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.40">

  <meta name="author" content="Professor Sarah Bauerle Danzman">
  <meta name="dcterms.date" content="2026-07-28">
  <title>INTL 503 — International Political Economy – Economic Coercion and Economic Statecraft</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2c51baf0c2adc8025befded91fc35e78.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="iu-trident.png" data-background-position="2% 2%" data-background-size="15%" class="quarto-title-block center">
  <h1 class="title">Economic Coercion and Economic Statecraft</h1>
  <p class="subtitle">INTL 503 | Economic Coercion</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor Sarah Bauerle Danzman 
</div>
</div>
</div>

  <p class="date">July 28, 2026</p>
</section>
<section id="todays-plan" class="slide level2">
<h2>Today’s Plan</h2>
<div class="callout callout-important no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Today’s Big Question</strong></p>
</div>
<div class="callout-content">
<p><span style="font-size: 1.4em; line-height: 1.4;"><strong>Economic exchange has always been a source of leverage — so why does today’s version feel so blatant, and so arbitrary?</strong></span></p>
</div>
</div>
</div>
<div id="tbl-plan" class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="font-size: 22px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Section</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">What we'll cover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 40%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">1 · Exchange as Leverage, Then and Now</td>
<td style="text-align: left; width: 60%;">An old tool in a new setting — from ancient embargoes to today's chokepoints</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 40%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">2 · Two Logics: Compel or Deny</td>
<td style="text-align: left; width: 60%;">Sanctions ask for something; export controls don't — different tools, different tests</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 40%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">3 · Weaponized Interdependence — and Its Critics</td>
<td style="text-align: left; width: 60%;">Farrell &amp; Newman's hub theory, and where other scholars push back</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 40%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">4 · Does Coercion Work?</td>
<td style="text-align: left; width: 60%;">Drezner's evidence on sanctions: more effective, and more costly, than assumed</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 40%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">5 · Denial in Practice: Export Controls</td>
<td style="text-align: left; width: 60%;">COCOM, semiconductors, and investment screening as capability denial</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 40%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">6 · Discussion: The Readings in Tension</td>
<td style="text-align: left; width: 60%;">Small groups argue the readings against each other, live, in class</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 40%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">7 · Synthesis: Coercion Across the Whole Course</td>
<td style="text-align: left; width: 60%;">Tying coercion back to the whole course's story of globalization</td>
</tr>
</tbody>
</table>


</div>
</div>
<aside class="notes">
<p>Today is the one day in this unit with no Oatley chapter. You read two articles — Farrell and Newman’s “Weaponized Interdependence” and Drezner’s 2024 review of the sanctions literature — and the session is built around them rather than around a chapter. It’s also built differently on purpose: more of today is discussion than lecture, and I want you arguing with these two pieces, not just absorbing them.</p>
<p>One logistics note, since the format is different: there is no reading reflection or writing due before class today. Every bit of writing and discussion happens here, live, in the room. That’s deliberate — I’d rather see your own thinking worked out in real time than a polished response you had days to prepare.</p>
<p>The arc: we open with a much longer look at history than you might expect for a “current events” topic, because the first thing I want to correct is the idea that any of this is new. Then we separate two logics that get run together in casual talk — compelling a target versus denying it something outright. Then Farrell and Newman’s theory of networks and hubs, alongside the real scholarly pushback on it, since I’m not going to teach that framework as settled fact. Then Drezner’s evidence on whether sanctions actually work. Then export controls get their own section, since that’s where I think the sanctions literature blurs something important. Then a discussion block that’s actually structured group work, not a single question at the end. Then synthesis. Every section title here will reappear as a crimson divider — use them as your map.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-we-start-a-ten-minute-write" class="slide level2">
<h2>Before We Start: A Ten-Minute Write</h2>
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>Writing prompt.</strong> Pick one economic relationship you already know from this course — the dollar’s role in world payments, a multinational’s supply chain, a government’s sovereign debt. Write for ten minutes: how could a government turn that relationship into leverage over another state? And once you’ve described it — would you call that ordinary statecraft, or something closer to an abuse of the system? Defend your answer.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Run this cold, no assigned reading required to attempt it — the point is to get you generating the intuition yourselves before we hand you any vocabulary for it. Give them the full ten minutes. When you debrief, don’t rush to supply the “correct” terms; just collect a few answers and note which ones already sound like sanctions, which sound like export controls, and which felt to the student like a foul rather than a normal move. Hold onto that last distinction — normal move versus foul — because it’s exactly the intuition the “blatant and arbitrary” language in the Big Question is trying to name, and we’ll come back to it explicitly in section six.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="exchange-as-leverage-then-and-now" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Exchange as Leverage, Then and Now</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Section 1</span></p>
</div>
</section>
<section id="the-politics-of-globalization-weaponized" class="slide level2">
<h2>The Politics of Globalization, Weaponized</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>This whole course has been about <strong>who wins and loses from economic openness</strong> — trade, money, multinationals, finance.</p>
<p>Today adds a second question on top of the first:</p>
<ul>
<li>Exchange doesn’t just create winners and losers — it can be <strong>turned into a lever</strong></li>
<li><strong>Economic statecraft</strong> — using economic means to pursue strategic or political goals</li>
<li><strong>Economic coercion</strong> — deliberately imposing or threatening economic costs to change a target’s behavior</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>The addition, not a replacement.</strong> Every distributive question from earlier in the course still applies. Today’s material sits on top of it: exchange as leverage, not just as a source of gains and losses.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Same connections you’ve studied all semester — a supply chain, a currency, a debt — examined now for what they let one government do <em>to</em> another.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Ground this in the whole course before you go anywhere near “weaponized interdependence,” because the concept only lands if students see it as an addition to what they already know, not a brand-new subject. Oatley’s book, and this course following it, has been asking one question over and over: when a country opens itself to trade, capital, or multinational production, who gains and who pays the adjustment cost? That’s a distributive question, and it’s run through every unit so far — comparative advantage’s winners and losers, the politics of exchange rates, who bears a debt crisis.</p>
<p>Today doesn’t replace that question. It adds one on top: the same flows of goods, money, and ownership that produce those distributive effects can also be picked up and used as an instrument — deliberately, by a government, against another government. Economic statecraft is the umbrella term for that: using economic means, carrots or sticks, to pursue a strategic or political goal. Economic coercion is the sticks end specifically — imposing or threatening economic costs to change what a target does. Sanctions are the most familiar form, but as you’ll see today, coercion is broader than sanctions.</p>
<p>The callouts make the framing explicit: this is additive, not a pivot away from everything else you’ve learned. Every supply chain, currency arrangement, and debt relationship you’ve studied is also, seen from this angle, a potential lever.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="leverage-before-the-twentieth-century" class="slide level2">
<h2>Leverage Before the Twentieth Century</h2>
<div id="tbl-history-early" class="cell">
<div class="cell-output-display">
<table class="table caption-top" data-quarto-postprocess="true" style="font-size: 21px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Case</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">What happened</th>
<th data-quarto-table-cell-role="th" style="text-align: left; font-weight: bold; color: white !important; background-color: rgba(153, 0, 0, 255) !important;">Why it's worth knowing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 26%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Megarian Decree (Athens, 432 BCE)</td>
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 37%;">Pericles barred Megarian merchants from Athenian and allied harbors</td>
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 37%;">One grievance among several behind Sparta's decision for war — ancient sources disagree on how much it mattered</td>
</tr>
<tr class="even">
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 26%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Venice's trade ban on Ottoman lands (1462–64)</td>
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 37%;">Total Venetian trade embargo during Venice's war with the Ottoman Empire</td>
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 37%;">Historians call it Venice's chief foreign-policy tool against a rival power</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 26%; font-weight: bold; color: rgba(153, 0, 0, 255) !important;">Continental System &amp; Orders in Council (1806–12)</td>
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 37%;">Napoleon banned European trade with Britain; Britain blockaded Europe in return</td>
<td style="text-align: left; padding-top: 10px; padding-bottom: 10px; line-height: 1.3; width: 37%;">Enforcement collapsed under smuggling; Russia's 1810 defection helped trigger Napoleon's invasion</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Three different eras and three different targets, but the same underlying move each time: cut a rival off from goods, markets, or harbors, and make them pay a price for a policy you don’t control directly.</p>
</div>
</div>
</div>
<aside class="notes">
<p>The point of this slide is entirely negative — I want to take “this is new” off the table before we build anything else. Start with Athens. In 432 BCE Pericles barred merchants from Megara, a rival city-state, from the Athenian agora and every harbor in the Delian League. Thucydides lists it as one grievance among several behind Sparta’s decision to go to war; a comic playwright, Aristophanes, mocked it decades later as a trivial pretext; and modern historians genuinely disagree about how much economic weight it carried versus how much it was really about Spartan fear of Athenian power. Present it as the earliest documented case of a trade embargo used as a tool of statecraft short of war, not as a proven cause of that war — the disagreement itself is worth a sentence, because it previews a pattern we’ll see all day: people arguing about whether an economic weapon actually did the work attributed to it.</p>
<p>Jump nearly two thousand years to Venice, which historians describe as running a total trade ban against Ottoman territory as its chief foreign-policy tool during its wars with the Ottoman Empire in the 1460s. Different setting, same logic: deny a rival access to your markets and shipping, and extract an economic cost instead of a military one.</p>
<p>Then Napoleon’s Continental System, 1806 to 1812 — probably the most ambitious embargo in history before the twentieth century. Napoleon tried to close the entire European continent to British trade by decree; Britain answered with its own blockade, the Orders in Council, trying to close off Napoleon’s Europe right back. Both failed as pure economic instruments — smuggling was massive, and enforcement was uneven — but the political consequences were real: Russia’s decision to defect from the system in 1810 was a direct cause of Napoleon’s catastrophic 1812 invasion, and the British blockade’s interference with American shipping helped trigger the War of 1812. Two great powers, each betting that economic pressure could substitute for a military victory neither could fully secure. The bottom callout states the point directly: different centuries and different tools, but the same instinct — deny the rival something they need, and make the denial itself the source of leverage.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-economic-weapon-codified" class="slide level2">
<h2>The Economic Weapon, Codified</h2>
<div class="columns">
<div class="column" style="width:54%;">
<p>World War I gave the instinct a modern, institutional form:</p>
<ul>
<li>Britain’s naval blockade of Germany (1914–19) cut off food and raw materials — the 1916–17 “Turnip Winter”</li>
<li>The blockade <strong>continued after the November 1918 armistice</strong>, as leverage to force acceptance of Versailles’s terms, easing only in early 1919</li>
<li>Civilian death tolls from the blockade are <strong>genuinely disputed</strong> among historians — treat any single number with caution</li>
<li>The League of Nations wrote <strong>automatic, collective sanctions</strong> into Article 16 of its Covenant — a peacetime tool modeled directly on a wartime one</li>
</ul>
</div><div class="column" style="width:46%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>Nicholas Mulder’s argument</strong> (<em>The Economic Weapon</em>, 2022): the blockade’s perceived success convinced League architects that economic pressure could substitute for war. Even Woodrow Wilson, who helped write it in, called it “a terrible remedy.”</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>A tool built for total war, relabeled as a peacetime instrument of collective security — worth remembering when we ask, later, why today’s version can feel arbitrary.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>This is the hinge slide of the history section, because it’s where “ancient instinct” becomes “modern institution.” Britain’s blockade of Germany during the First World War went far beyond stopping munitions — it cut off food and raw materials to the whole civilian economy, producing real, severe hunger, memorialized in Germany as the “Turnip Winter” of 1916–17 when potatoes failed and turnips became a staple. Here’s the detail that should genuinely surprise students: the blockade did not end when the fighting did. The armistice of November 11, 1918 explicitly preserved it, and the Allies kept it in place for months afterward specifically to pressure Germany into accepting the Versailles terms; it only eased through agreements in early 1919 and was fully lifted around that summer. Winston Churchill told the House of Commons in March 1919 that Germany was “very near starvation.” That is coercion outlasting the war it was supposedly fought to end.</p>
<p>Flag honestly, in the left column, that the death toll from all this is a live historical argument, not a settled fact. Germany’s own 1918 wartime claim was roughly seven hundred sixty thousand blockade deaths; a 1928 revision by the historian N. P. Howard put it closer to four hundred twenty-five to four hundred seventy-five thousand; other historians, including Sally Marks, have called the whole “starvation blockade” narrative overstated, while more recent work using data on child growth, by Mary Cox, shows real and severe malnutrition even while acknowledging wartime propaganda exaggerated the numbers. Don’t give students a number to memorize; give them the dispute itself as the lesson — even a case this well documented resists a clean verdict on how much an economic weapon actually cost.</p>
<p>Now the theoretical payoff, which is Nicholas Mulder’s argument in his 2022 book “The Economic Weapon.” The blockade looked, to the diplomats designing the postwar order, like proof that economic pressure alone could bring a great power to its knees without more battlefield deaths. So the League of Nations wrote it directly into Article 16 of its Covenant: any member that went to war in violation of the Covenant would automatically face collective severance of trade and financial relations from every other member. Mulder’s sharpest observation, in the top callout, is that even Woodrow Wilson — who helped design this system and clearly believed in it — privately called sanctions “a terrible remedy.” The League’s peacetime security architecture was built on a wartime tool aimed at civilian populations, just relabeled as bloodless and modern. The bottom callout returns to this, because it’s exactly the tension in today’s Big Question: a tool built for total war, operating under the cover of ordinary peacetime policy, is going to feel different — more arbitrary, more contestable — than a declared blockade ever did, precisely because nobody declared anything.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="test-case-abyssinia-193536" class="slide level2">
<h2>Test Case: Abyssinia, 1935–36</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>Italy invaded Abyssinia (Ethiopia) in October 1935. The League’s Article 16 got its first real trial:</p>
<ul>
<li><strong>52 states</strong> joined a sanctions coalition within six weeks — arms embargoes, credit freezes, import bans</li>
<li>Coalition members deliberately <strong>excluded oil, coal, and iron</strong> — and left the Suez Canal open to Italian troop transports</li>
<li>Italian industrial output fell <strong><sub>21%<strong>, exports </strong></sub>47%</strong> — real damage, not enough to stop the war</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Mussolini reportedly told Hitler that an oil embargo alone would have forced Italy to withdraw within a week. The League never imposed one.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Sanctions lifted July 1936; Italy completed the conquest; League credibility collapsed. Mulder’s larger finding: historically, sanctions have achieved their stated goal, fully or partially, roughly a third of the time.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>This is the case Mulder’s book returns to again and again, and it earns a slide of its own because it does two jobs at once: it shows the League’s brand-new tool actually being used, and it previews the effectiveness debate that Drezner picks up later in modern form. When Mussolini’s Italy invaded Abyssinia in October 1935, the League moved with real speed by the standards of international diplomacy — fifty-two member states assembled a sanctions coalition within about six weeks, freezing credit, embargoing arms, and banning imports from Italy.</p>
<p>But look at what they left out, in the left column, because the omissions are the whole story. The coalition specifically declined to embargo oil, coal, and iron — Italy’s most critical war-fighting inputs — and left the Suez Canal open, so Italian troops and supplies kept flowing to East Africa the entire time. The sanctions did real economic damage: Italian industrial output fell by roughly a fifth, exports by nearly half — genuine harm, but not enough to change the outcome. In the top callout, Mulder reports that Mussolini later told Hitler that a genuine oil embargo would have forced an Italian withdrawal within a week — the League had identified the one lever that would have worked and chosen, for reasons of British and French self-interest in not alienating Italy further, not to pull it.</p>
<p>The sanctions were lifted in July 1936, Italy kept its conquest, and the League’s credibility as a guarantor of collective security never recovered — a failure that fed directly into the collapse of interwar diplomacy and the road to the Second World War. The bottom callout gives you Mulder’s larger statistical finding, which should recalibrate how confidently anyone talks about sanctions in either direction: across the full historical record he studied, sanctions have achieved their stated aim, fully or partially, only about a third of the time. Remember that number — it’s the direct ancestor of the effectiveness debate Drezner picks up in section four, and it should make you suspicious of anyone, in 1936 or in 2026, who’s fully confident sanctions will work.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="two-logics-compel-or-deny" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Two Logics: Compel or Deny</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Section 2</span></p>
</div>
</section>
<section id="sanctions-ask-export-controls-deny" class="slide level2">
<h2>Sanctions Ask; Export Controls Deny</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Compellence</strong> (sanctions, in the strict sense):</p>
<ul>
<li>Makes a demand of the target — change this policy, release this prisoner, withdraw these troops</li>
<li>Success means the target <strong>complies</strong></li>
<li>The demand is what makes the pressure legible as coercion, in Schelling’s sense, rather than simple denial</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Denial</strong> (export controls, technology restrictions):</p>
<ul>
<li>Removes an input or capability — no demand attached, no compliance to wait for</li>
<li>“Success” means the target simply <strong>doesn’t have it anymore</strong></li>
<li>The goal is a lasting capability gap, not a change of mind</li>
</ul>
</div></div>
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Drezner’s own definition of economic coercion (2003) requires a target that “acquiesces to an articulated demand.” That definition fits sanctions cleanly. It does not obviously fit a rule that says a category of technology may never be sold, to anyone, regardless of behavior.</p>
</div>
</div>
</div>
<aside class="notes">
<p>This slide gives you vocabulary that the rest of the day depends on, so take it slowly. Two different logics get called “sanctions” in casual conversation, and conflating them makes it hard to ask sharp questions about either one. The first is compellence: you make a specific, articulated demand of a target — leave this territory, release this person, stop this program — and you apply economic pressure until they comply. Success has a clear definition: the target does the thing you demanded. This is the logic Thomas Schelling described decades ago for coercive bargaining generally, and it’s the logic behind classic sanctions episodes.</p>
<p>The second is denial. Export controls on advanced semiconductors, or Cold War restrictions on machine tools to the Soviet bloc, don’t make a demand that the target can satisfy and thereby end the pressure. They simply remove access to an input. There’s no compliance pathway, because there’s no demand — the goal is a durable capability gap, not a change of policy. A target under an export-control regime can’t “give in”; there’s nothing to give in to.</p>
<p>The callout gives you the sharpest version of this distinction in the scholarly literature: Drezner’s own 2003 definition of economic coercion requires that the target “acquiesce to an articulated demand.” That’s a clean fit for compellent sanctions. Ask yourself whether it’s a clean fit for a rule that bars a whole category of chips from ever being sold to a rival, no matter what that rival does. It isn’t, and that mismatch is exactly why today’s session treats these as two logics rather than one.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-were-separating-them-today" class="slide level2">
<h2>Why We’re Separating Them Today</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>Drezner’s 2024 review is the best available synthesis of the sanctions-effectiveness literature. It is less careful about <strong>scope</strong> — export-control cases sit inside the same review alongside compellent sanctions.</p>
<p><strong>What that means for today:</strong></p>
<ul>
<li>Section 4 keeps Drezner’s evidence, scoped tightly to <strong>compellent sanctions</strong></li>
<li>Section 5 gives export controls their <strong>own</strong> history and their own test for success</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Drezner’s findings stand — this is a scope correction, not a rejection of them. A finding about whether compellence works tells you little about whether denial works, because they’re not attempting the same thing.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Be transparent with students about an analytical choice you’re making, because it models exactly the kind of critical reading you want from them with both assigned pieces. Drezner’s review is genuinely the strongest available synthesis of what decades of sanctions research have found, and section four keeps all of it. But a review essay covering “economic sanctions” broadly will naturally pull in cases — export-control episodes among them — that don’t share the compellence logic the effectiveness literature is actually testing.</p>
<p>So here is the choice, and say it plainly: this course is going to keep Drezner’s evidence scoped to compellent sanctions, where “does it work” has a clean meaning — did the target comply. Export controls get their own section, with their own history and their own test of success, which is about durable capability gaps, not compliance. In the callout: this is not a takedown of Drezner. It’s a scope correction, and scope corrections are one of the most useful things you can do with a strong synthesis piece — keep what it establishes, and be precise about what it wasn’t built to answer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="weaponized-interdependence-and-its-critics" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Weaponized Interdependence — and Its Critics</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Section 3 · Farrell &amp; Newman 2019</span></p>
</div>
</section>
<section id="networks-have-hubs-and-hubs-have-power" class="slide level2">
<h2>Networks Have Hubs — and Hubs Have Power</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>Farrell &amp; Newman’s core claim: global economic networks are <strong>not flat.</strong></p>
<ul>
<li>An <strong>asymmetric topology</strong> — a few central hubs, many peripheral nodes — emerges because shared infrastructure is more efficient than bilateral links</li>
<li>Two things a hub-controlling state can do: the <strong>panopticon effect</strong> (watch what flows through) and the <strong>chokepoint effect</strong> (cut a target off from it)</li>
<li><strong>SWIFT</strong> is the clearest example: U.S. access to SWIFT data tracked terrorist financing after 9/11 (panopticon); Iran (2012) and Russia (2022) were disconnected from it (chokepoint)</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>The key claim.</strong> Power doesn’t come from how <em>much</em> you trade. It comes from <em>where you sit</em> in the network — control of the node everyone else routes through.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>This is a structural theory: the shape of the network does the explaining, not the wealth of any one country.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Here is Farrell and Newman’s central move, and you should be able to state it crisply. Global economic networks aren’t flat meshes where everyone connects directly to everyone else. Picture a payments map: it looks like an airline route map, a small number of giant hubs that nearly everything routes through, and a large periphery that connects to the rest of the world only via those hubs. Nobody designed the hubs as weapons — they emerged because shared infrastructure is cheaper than a web of bilateral links. But once a hub exists, the state with legal jurisdiction over it inherits real leverage over everyone who depends on it.</p>
<p>Two distinct things follow from controlling a hub. The panopticon effect is surveillance: because transactions route through your jurisdiction, you can watch them. After 9/11, U.S. access to SWIFT messaging data let intelligence agencies trace terrorist financing across borders — nobody was cut off, the U.S. was simply watching what already flowed through the hub. The chokepoint effect is denial: because the periphery depends on the hub to function, you can sever a target from it entirely. Iranian banks were disconnected from SWIFT in 2012; major Russian banks were disconnected in 2022. One hub, two distinct capabilities.</p>
<p>The callouts carry the theoretical weight. Power here doesn’t track raw economic size — it tracks position. A mid-sized economy that happens to host a critical hub can out-coerce a much larger economy sitting on the network’s edge. That’s a structural theory of power: the map explains the outcome, not any single country’s wealth. We’ll come back to whether that’s entirely right in a couple of slides.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-dollar-as-the-master-hub" class="slide level2">
<h2>The Dollar as the Master Hub</h2>
<div class="columns">
<div class="column" style="width:54%;">
<p>The dollar is the most powerful chokepoint of all:</p>
<ul>
<li>Most cross-border trade and finance is invoiced and settled in dollars — connecting back to Chapter 10’s “exorbitant privilege”</li>
<li>Dollar payments ultimately clear through U.S. banks, giving U.S. authorities <strong>legal reach over almost any dollar transaction, anywhere</strong></li>
<li>A foreign bank that helps a sanctioned entity risks losing dollar access — often a corporate death sentence</li>
</ul>
</div><div class="column" style="width:46%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>You don’t have to trade <em>with</em> the U.S. to be exposed. If your transaction touches the dollar — and almost everything does — it touches U.S. jurisdiction.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>Secondary sanctions</strong>: the U.S. threatens third parties who deal with the target, leveraging the whole world’s need for the dollar.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>If SWIFT is the messaging hub, the dollar is the master hub. Tie this straight back to the monetary unit — Chapter 10’s exorbitant privilege — because it’s the same underlying fact seen from a different angle. Most international trade is invoiced in dollars, most cross-border lending is in dollars, most reserves are held in dollars. That dominance is built on ordinary economic logic: the dollar is liquid and stable, so it keeps getting used.</p>
<p>The coercive payoff is technical but decisive: dollar payments, even between two non-American parties, ultimately clear through the U.S. banking system via correspondent accounts. That means almost any dollar transaction on earth passes through U.S. jurisdiction at some point, whether or not the United States is a party to it. A foreign bank processing payments for a sanctioned entity can be told: continue, and lose dollar clearing access — for a major bank, close to a death sentence.</p>
<p>That’s secondary sanctions, in the bottom callout. Primary sanctions restrict Americans from dealing with the target. Secondary sanctions go further: anyone, anywhere, who deals with the target risks losing access to the dollar system. Because everyone needs the dollar, the U.S. can effectively conscript the world’s banks into enforcing its sanctions. You don’t have to trade with America to be exposed — you only have to touch the dollar, and almost everything does.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="open-questions-about-this-theory" class="slide level2">
<h2>Open Questions About This Theory</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>This is an influential framework, not a settled consensus. Three lines of pushback worth carrying into discussion:</p>
<ul>
<li><strong>Private agency.</strong> Firms, not governments, actually build and run most network infrastructure — do they behave the way a purely structural theory predicts? (Gjesvik 2023)</li>
<li><strong>Erosion through use.</strong> Repeatedly weaponizing the dollar gives everyone watching a reason to build an alternative — does that make the power more fragile than the theory suggests? (McDowell 2023, <em>Bucking the Buck</em>)</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><strong>An older argument, unacknowledged.</strong> Some scholars argue “weaponized interdependence” substantially rediscovers dependency theory’s claim that asymmetric interdependence is exploitable — without engaging that literature (Palestini 2026)</li>
</ul>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>I’m not going to resolve these for you. Hold onto all three — we’ll put them to work directly in today’s discussion.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Say this plainly to the class: Farrell and Newman’s article is genuinely influential, and it gave the field useful vocabulary, but it is not the last word, and I don’t want you treating it as settled the way you might treat, say, the Stolper-Samuelson result. Three critiques are worth carrying forward.</p>
<p>First, private agency. Lars Gjesvik points out that hubs are mostly built and operated by private firms making commercial decisions, not governments — a payments company or a cloud provider has its own reasons for where it locates infrastructure, and its own incentives around compliance. A purely structural account, where jurisdiction over a hub mechanically converts into usable state power, has to explain why firms go along, and doesn’t always.</p>
<p>Second, erosion through use. Daniel McDowell’s research on de-dollarization argues that every time the dollar system gets weaponized, it teaches everyone watching — not just the target — that dollar access is conditional and political, and that lesson pushes people to build alternatives. If using the chokepoint corrodes the chokepoint, the “structural power” in the theory is less stable and more self-limiting than it first appears.</p>
<p>Third — and this is the one I most want you to spend time on — Stefano Palestini’s recent argument that “weaponized interdependence” substantially rediscovers a claim dependency theorists made decades ago, that asymmetric interdependence is a source of exploitable power, without engaging that older literature at all. If you’ve encountered dependency theory in another course, ask yourself what’s actually new here versus what’s a new vocabulary for an old insight.</p>
<p>I’m handing you these three, in the callout, without resolving them, on purpose. We’re using them directly in the discussion section later today.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="does-coercion-work" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Does Coercion Work?</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Section 4 · Drezner 2024 · scoped to compellent sanctions</span></p>
</div>
</section>
<section id="the-sanctions-debate-has-moved" class="slide level2">
<h2>The Sanctions Debate Has Moved</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>Drezner reviews where the field has gone since Baldwin’s <em>Economic Statecraft</em> (1985):</p>
<ul>
<li><strong>Old consensus:</strong> “sanctions rarely work” — costly signals that mostly fail to change behavior</li>
<li><strong>Newer findings:</strong> careful measurement shows coercion is <strong>more effective than once believed</strong></li>
<li>Coercion succeeds more often when it is multilateral, institutionalized, and hits constituencies the target government actually depends on</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>Drezner’s headline.</strong> Sanctions work <em>better</em> than the old pessimism claimed — <strong>but</strong> their unintended costs and externalities are <em>far larger</em> than once understood.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Two corrections, moving in opposite directions: less pessimistic about effectiveness, more worried about side effects. Keep them separate.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Now the evidence, scoped as we agreed — this is about compellent sanctions specifically. Drezner’s review essay takes stock of the field since David Baldwin’s 1985 book set its agenda. For a long time, the dominant impression, sometimes a caricature of more careful work underneath it, was pessimistic: sanctions rarely change a target’s behavior, and mostly let leaders look tough while the target absorbs the pain.</p>
<p>Drezner’s review says that picture has shifted, and be precise about how. As scholars got better at measuring outcomes — including cases where the threat of sanctions produced concessions before anything was ever imposed — the evidence turned out less pessimistic than the old consensus held. Coercion is more effective than once believed, and the literature has learned when: multilateral efforts succeed more than unilateral ones, especially when institutionalized and including the target’s major trading partners, and sanctions succeed more often when they hit the specific domestic constituencies a government actually depends on.</p>
<p>But the actual headline, in the top callout, is the second half. The same body of research that revised effectiveness upward also revised costs upward, sharply. The externalities and unintended consequences of sanctions are far larger than the field once understood. Keep both halves in view, per the bottom callout — students like to flatten this into one verdict, “sanctions work” or “sanctions are bad.” Drezner is saying both things, about different dimensions, and the tension between them is the actual finding.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="smart-sanctions-and-their-limits" class="slide level2">
<h2>Smart Sanctions and Their Limits</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>The policy answer to “sanctions hurt civilians” was <strong>targeted (“smart”) sanctions:</strong></p>
<ul>
<li>Hit elites, regime cronies, and specific firms — not the whole population</li>
<li>Asset freezes, travel bans, blacklisting individual entities</li>
<li>The 1990s Iraq experience (mass civilian suffering, regime survival) drove the shift</li>
</ul>
<p>But the costs did not vanish — they <strong>moved and grew:</strong></p>
<ul>
<li>Financial over-compliance and de-risking strand legitimate trade</li>
<li>Humanitarian and third-country spillovers persist</li>
</ul>
</div><div class="column" style="width:50%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>The trade-off Drezner stresses.</strong> Targeting made sanctions more usable and more frequent — and because they’re now used constantly, the systemic externalities keep piling up.</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Targeting improved on blunt embargoes. It also lowered the threshold to sanction, so the tool gets reached for far more often.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>One of Drezner’s most important threads is the rise of “smart” or targeted sanctions, and understanding why they emerged tells you why they didn’t solve the underlying problem. Comprehensive embargoes hammer ordinary people — the defining cautionary tale is Iraq in the 1990s, where a sweeping embargo produced severe civilian suffering while Saddam Hussein remained in power. The response was to target specific individuals and entities instead: freeze the assets of regime elites, ban them from travel, blacklist particular firms — punish the decision-makers, spare the population.</p>
<p>Targeting was real progress, and Drezner credits it. But notice the costs didn’t disappear; they relocated and, in aggregate, grew. Banks facing the threat of secondary sanctions become so risk-averse that they refuse to handle whole categories of perfectly legal business — entire countries, charities, remittance corridors — because the risk of an error isn’t worth it. This is over-compliance or de-risking, and it strands legitimate trade well beyond the intended target.</p>
<p>The more important point, in the top callout, is Drezner’s actual argument: by looking more precise and humane, targeting made sanctions more politically usable, which lowered the threshold for reaching for the tool at all. We now sanction constantly, across an ever-growing list of targets, and because the tool is used so much more often, the system-wide externalities keep accumulating. Smart sanctions didn’t remove the cost — they lowered the apparent cost of each individual use, so the tool gets used far more often, and the aggregate cost keeps climbing.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="denial-in-practice-export-controls" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Denial in Practice: Export Controls</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Section 5</span></p>
</div>
</section>
<section id="cocom-the-cold-war-denial-regime" class="slide level2">
<h2>COCOM: The Cold War Denial Regime</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>The Cold War already ran a full-scale denial regime, decades before “chokepoints” entered the vocabulary:</p>
<ul>
<li><strong>COCOM</strong> (1949–94): the U.S. and allies shared lists of strategic and dual-use goods barred from sale to the Soviet bloc</li>
<li><strong>1982:</strong> the Siberian pipeline dispute — Reagan sanctioned European firms building a Soviet gas pipeline; allies pushed back, and the U.S. reversed course</li>
<li><strong>1987:</strong> the Toshiba-Kongsberg scandal — Toshiba sold submarine-quieting machine tools to the USSR, costing it roughly <strong>$1B</strong> in lost U.S. sales</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>COCOM was disbanded in 1994 and succeeded by the looser Wassenaar Arrangement in 1996 — multilateral denial regimes are hard to sustain once the common threat that built them fades.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Export controls have their own history, and it’s worth knowing before we get to semiconductors, because it shows both how denial regimes work and how hard they are to hold together. From 1949 to 1994, the United States and its allies ran COCOM — the Coordinating Committee for Multilateral Export Controls — sharing lists of strategic and dual-use goods that member countries agreed not to sell to the Soviet bloc. No demand was being made of Moscow; the goal was simply to keep certain capabilities out of Soviet hands, indefinitely.</p>
<p>Two episodes show the regime’s real tensions. In 1982, the Reagan administration tried to block European firms from supplying a Siberian natural-gas pipeline to the USSR, extending U.S. export-control authority onto foreign subsidiaries of American companies; European governments saw this as regulatory overreach and pushed back hard enough that Washington reversed the sanctions. In 1987, Toshiba was caught having sold Soviet submarines quieting technology — milling machinery that made Soviet subs harder to detect — a scandal that cost the company roughly a billion dollars in lost American sales and access.</p>
<p>COCOM itself didn’t survive the Cold War it was built for; it was disbanded in 1994 and replaced by the much looser, non-binding Wassenaar Arrangement in 1996. The callout is the lesson to carry forward into the chip-controls discussion: multilateral denial regimes work only as long as every participant shares the sense of threat that justified giving up commercial revenue in the first place, and that consensus is fragile.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="chips-as-the-chokepoint-now" class="slide level2">
<h2>Chips as the Chokepoint Now</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>October 2022: the U.S. imposed sweeping export controls on advanced semiconductors and chipmaking equipment bound for China.</p>
<ul>
<li>The goal, per contemporaneous policy analysis, was to <strong>degrade</strong> China’s current chipmaking capability — not merely slow its future advance</li>
<li>No demand was attached — this is denial, in section 2’s sense, not compellence</li>
<li>The chokepoints: a handful of firms make the extreme-ultraviolet lithography tools advanced chips require</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>This is Farrell &amp; Newman’s chokepoint mechanism doing real work — a small number of irreplaceable nodes in a supply chain, and jurisdiction over them converted into a denial tool.</p>
</div>
</div>
</div>
</div></div>
<p><span style="font-size:0.85em; color:#535054;">🎧 <strong>Today’s podcast</strong> — <em>Trade Talks</em> ep. 170, <em>“National Security, Semiconductors, and the US Move to Cut Off China”</em> — this case, from the inside.</span></p>
<aside class="notes">
<p>Now the case everyone already half-knows. In October 2022, the U.S. announced sweeping restrictions on exporting advanced semiconductors, and the equipment used to make them, to China. Contemporaneous policy analysis described the goal precisely: degrade China’s current chipmaking capability outright, well beyond merely slowing its future progress at the frontier. There’s no demand attached to this — nobody is asking Beijing to change a policy in exchange for relief. It’s denial in exactly the sense we defined in section two.</p>
<p>Why does this work at all? Because the chip supply chain has genuine chokepoints — a tiny number of firms make the extreme-ultraviolet lithography machines that advanced chip fabrication requires, and controlling access to that narrow set of tools lets the U.S. and a few allies reach deep into a capability that China cannot easily replace domestically, at least not quickly. This is Farrell and Newman’s mechanism operating exactly as the theory predicts: a small number of irreplaceable nodes, and jurisdiction over them converted into leverage. Point to the podcast: today’s Trade Talks episode covers this case from the inside, and it’s worth assigning as background before the discussion block.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-unilateral-denial-tends-to-fail" class="slide level2">
<h2>Why Unilateral Denial Tends to Fail</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>Denial regimes share a structural problem: <strong>substitution.</strong></p>
<ul>
<li>A target cut off from one supplier has an incentive to build its own capacity, or buy from someone who isn’t participating in the controls</li>
<li>Controls imposed by one country alone create an opening for competitors who don’t share the restriction</li>
<li>Bauerle Danzman &amp; Kilcrease (<em>Foreign Affairs</em>, 2022): unilateral U.S. controls on China’s technology ambitions are likely to fail without close allied coordination</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>The same logic as COCOM’s 1982 pipeline dispute and its 1994 collapse: a denial regime is only as strong as the coalition willing to give up revenue to sustain it.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Denial regimes have a structural weakness that compellent sanctions don’t share in the same way: substitution. If you’re denied a chip, or a machine tool, and the denial has no expiration tied to your behavior, your incentive is to build the capability yourself or find a supplier who isn’t part of the coalition enforcing the restriction. And if the restriction is unilateral, competitors who aren’t bound by it have every incentive to fill the gap you just created — for their own commercial benefit, not out of any principle.</p>
<p>I’ll draw on my own work here, with Emily Kilcrease, arguing exactly this in Foreign Affairs in 2022: unilateral U.S. attempts to contain China’s technology ambitions are likely to fail unless they’re closely coordinated with allies who control adjacent parts of the same supply chain. Act alone, and you mostly hand the business to a rival supplier while accelerating the target’s investment in indigenous capacity — which is close to the worst of both outcomes. Tie this back to COCOM, in the callout: the 1982 pipeline dispute and the regime’s eventual 1994 collapse are the same lesson in an earlier setting. A denial regime holds together only as long as every participant is willing to keep giving up revenue for it, and that willingness erodes.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="screening-at-the-point-of-entry" class="slide level2">
<h2>Screening at the Point of Entry</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>Denial doesn’t only run through exports — it also runs through <strong>who is allowed to buy in.</strong></p>
<ul>
<li><strong>Investment screening</strong> regimes (the U.S. CFIUS, and dozens of similar bodies built worldwide over the past decade) review and can block foreign acquisitions on national-security grounds</li>
<li>The PRISM dataset (Bauerle Danzman &amp; Meunier, <em>ISQ</em> 2023) maps these mechanisms across nearly 100 countries — screening has become a global, not just American, instrument</li>
</ul>
</div><div class="column" style="width:48%;">
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>This is the <strong>securitization of political economy</strong>: ordinary cross-border investment — who can buy what company — increasingly treated as a national-security question, with regulatory machinery built to police it.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>One more form of denial, and it’s the one I work on most directly: denial at the point of entry, through investment screening. In the United States, that’s CFIUS, which you met back in Chapter 9; over the past decade, dozens of other countries have built similar review bodies of their own. These regimes let a government block a foreign acquisition before it happens, on national-security grounds — denial applied not to an export, but to ownership itself.</p>
<p>The PRISM dataset I built with Sophie Meunier, published in International Studies Quarterly in 2023, maps these mechanisms across nearly a hundred countries, and the pattern is unmistakable: this is now a global instrument, not an American peculiarity. In the callout, the frame I use for this in my own research is the securitization of political economy — the process by which ordinary cross-border investment decisions, who is allowed to buy what company, get redefined as national-security questions, with new regulatory machinery built specifically to police that boundary. Keep this in mind for the discussion block: screening is a quieter, more procedural form of denial than an export ban or a frozen reserve, and that quietness is itself worth interrogating — is it less coercive because it’s less visible, or just less examined?</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="discussion-the-readings-in-tension" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Discussion: The Readings in Tension</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Section 6</span></p>
</div>
</section>
<section id="how-today-works" class="slide level2">
<h2>How Today Works</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>No pre-class reflection, no prepared answers — everything below happens live, in breakout groups, starting now.</p>
<p><strong>Round 1 (small groups, ~12 min):</strong></p>
<ul>
<li>Half the groups take <strong>Farrell &amp; Newman</strong>; half take <strong>Drezner</strong></li>
<li>Each group answers its assigned prompts using only what’s in front of you today — the reading, the slides, your own ten-minute write</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Round 2 (regroup, ~12 min):</strong></p>
<ul>
<li>Re-mix into pairs with one person from each side</li>
<li>Each person explains their article to their partner; together, find one place the two readings <strong>agree</strong>, and one place they <strong>talk past each other</strong></li>
</ul>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Whole-class debrief follows — be ready to name your pair’s tension point out loud.</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Explain the mechanics before you start the clock, because this format is different from a normal cold-call discussion and students do better with the shape laid out up front. Nobody prepared anything for this in advance — that’s by design, so what you hear is genuinely live thinking, not a rehearsed answer. First round: split into small groups, half assigned to Farrell and Newman, half to Drezner, each working the assigned prompts on the next slide using only what’s already in the room — the article, today’s slides, and whatever came out of the opening ten-minute write. About twelve minutes.</p>
<p>Second round: break those groups up and re-form pairs with one person from each side. Each person has to explain their article to a partner who’s spent the last twelve minutes immersed in the other one — that’s the real test of whether they understood it, not just skimmed it. Together, the pair finds one point where the two readings actually agree, and one point where they’re answering different questions entirely, or working from incompatible assumptions, even though they sound like they’re in the same conversation. About twelve minutes again. Then a whole-class debrief where you’ll cold-call pairs to report their tension point — tell them that up front so nobody coasts.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="discussion-prompts" class="slide level2">
<h2>Discussion Prompts</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Farrell &amp; Newman groups:</strong></p>
<ul>
<li>Gjesvik says private firms, not states, actually run most hubs. Where in the article does the theory depend on firms simply going along with state pressure?</li>
<li>If using a chokepoint erodes it (McDowell), is “structural power” the right name for something this unstable?</li>
<li>Mulder’s Abyssinia case: the League controlled a chokepoint (oil) and chose not to use it. What does that do to a theory that treats hub control as automatically convertible into power?</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Drezner groups:</strong></p>
<ul>
<li>Drezner’s own 2003 definition of coercion requires “an articulated demand.” Find a case in the 2024 review that doesn’t obviously fit that definition. What is it actually doing?</li>
<li>“Smart” sanctions were supposed to lower civilian costs. Drezner says they instead lowered the <em>political</em> cost of sanctioning. Is that a success or a failure of the reform?</li>
<li>Mulder’s finding — sanctions succeed, fully or partially, about a third of the time historically. Does Drezner’s more optimistic modern evidence update that number, or answer a different question?</li>
</ul>
</div></div>
<aside class="notes">
<p>These are the prompts for round one — read them out, or post them, and then get out of the way. Notice each set is built to force the group back into the article rather than into generalities, and each also reaches back into today’s earlier sections, so the two groups arrive at the pairing exercise already primed to find real friction rather than surface agreement. The Farrell and Newman prompts pull directly from section three’s critiques and from the Abyssinia case in section one — a state (Britain, France) that controlled a real chokepoint (oil) and declined to use it is a direct challenge to any reading of the theory where hub control converts automatically into coercive power. The Drezner prompts pull from section two’s compellence/denial distinction and from Mulder’s historical base rate. Don’t resolve any of these for the groups when you circulate — your job in round one is only to make sure nobody is stuck, not to supply the answer.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="debate-name-the-thing-correctly" class="slide level2">
<h2>Debate: Name the Thing Correctly</h2>
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>Whole-class debate prompt.</strong> Farrell and Newman call this “weaponized interdependence” — language that implies something has changed about interdependence itself. Given everything from Megara to Abyssinia to COCOM: is that the right name, or is this just economic statecraft, running on newer infrastructure?</p>
</div>
</div>
</div>
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Take a side. Argue it. Then argue the other side. Today’s goal is to notice how much your answer depends on how much weight you put on the history, not to reach a final verdict.</p>
</div>
</div>
</div>
<aside class="notes">
<p>Close the discussion block with this as a genuine whole-class debate, not a rhetorical question you answer yourself. Split the room, or ask for volunteers, and have one side argue that “weaponized interdependence” is the right name — something really has changed, the density and concentration of today’s networks are qualitatively different from a naval blockade or a Cold War export list, and that difference deserves a new name. Have the other side argue that this is a relabeling exercise — Megara, Venice, the Continental System, the WWI blockade, COCOM: economic leverage aimed at a rival is exactly what states have always done, and giving it a new name risks making it sound more novel, and more theoretically clean, than it actually is.</p>
<p>Don’t let the class settle for a tidy middle position too quickly. The answer likely depends on how much weight you put on the historical continuity versus the structural changes in scale and concentration — and that’s a judgment call, not a fact to look up. This is also the moment to be candid, if it comes up, that I don’t fully sign on to the “weaponized interdependence” framing myself, for reasons close to what you’ve just been debating — and that’s a conversation I want to have with you directly, not just embed in a slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="synthesis-coercion-across-the-whole-course" class="title-slide slide level1 center" data-background-color="#990000">
<h1>Synthesis: Coercion Across the Whole Course</h1>
<div style="text-align:center; margin-top:-0.2em;">
<p><span style="font-size:0.6em; color:#EDEBEB; letter-spacing:0.15em;">Section 7</span></p>
</div>
</section>
<section id="the-whole-course-twice-over" class="slide level2">
<h2>The Whole Course, Twice Over</h2>
<div class="callout callout-important no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p><strong>Today’s Big Question —</strong> Economic exchange has always been a source of leverage. Why does today’s version feel so blatant, and so arbitrary?</p>
</div>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="whats-old">What’s old</h3>
<ul>
<li>Turning exchange into leverage goes back at least to Athens and Megara — sanctions, embargoes, and blockades are ancient tools</li>
<li>Sanctions have always had a mixed record — Mulder’s rough historical base rate is one-in-three</li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="whats-arguably-different">What’s arguably different</h3>
<ul>
<li>Today’s version runs through <strong>peacetime civilian infrastructure</strong> — payment rails, licensing regimes — not a declared blockade, which is part of why it can feel arbitrary rather than lawful</li>
<li>Every unit of this course — trade, money, MNCs, finance — turns out to have a coercive edge</li>
</ul>
</div></div>
<aside class="notes">
<p>Pull the day together against the Big Question, which asked why something this old feels this new. The “old” side is now well established: turning economic exchange into leverage is at least twenty-five hundred years old, and even the most sophisticated version of it — the League of Nations’ Article 16 — had, by Mulder’s count, roughly a one-in-three historical success rate. None of this is a recent invention.</p>
<p>What’s arguably different is on the right, and it’s a genuine claim, not just a restatement of Farrell and Newman. A declared naval blockade in 1915 was, whatever else it was, an openly declared act, understood by everyone as a wartime measure with a wartime logic. Today’s version — an entity added to a list, a bank quietly told its correspondent relationship is at risk, an export license denied — runs through the ordinary administrative processes of peacetime, has no clear declaration or endpoint, and touches parties who never agreed to anything resembling a state of war. The underlying instinct hasn’t changed; the setting it now operates in no longer announces itself as exceptional, and that’s a real part of why it can feel more arbitrary.</p>
<p>The last point ties back to the entire semester: trade, money, multinational production, and international finance — every pillar of this course — turns out to have a coercive edge once you examine it through today’s lens. Each of those units taught you how exchange generates prosperity and distributes its costs; today added that the same exchange can be picked up and used as a lever. Both things are true of the same material at once, and holding both is the point of today.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="what-to-keep-from-today" class="slide level2">
<h2>What to Keep From Today</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>Three things worth keeping, regardless of where you landed in the debate:</p>
<ul>
<li><strong>The compellence/denial distinction</strong> — ask, of any policy called a “sanction,” which logic it’s actually running on</li>
<li><strong>A base rate for skepticism</strong> — coercion has never worked as reliably as its advocates claim, or as unreliably as its critics claim</li>
<li><strong>A habit of checking the theory against the history</strong> — Farrell &amp; Newman’s mechanism is real; so are its limits</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="callout callout-tip no-icon callout-style-simple">
<div class="callout-body">
<div class="callout-content">
<p>Next time we meet, we return to the textbook — and to a question this unit has been quietly building toward: what happens when the countries that write these rules are not the only ones with leverage left to use?</p>
</div>
</div>
</div>
</div></div>
<aside class="notes">
<p>Close with three durable habits rather than a summary of facts, since facts fade and habits transfer to the next case they encounter, in this course or after it. First, whenever you hear something called a “sanction” in the news, ask which logic it’s actually running on — compellence, with a demand attached, or denial, with none. That single question will clarify most headlines you read from here on. Second, apply a base rate for skepticism to any claim about whether coercion “works”: across a century of evidence, it works often enough to keep getting used and fails often enough that nobody should be fully confident going in. Third, keep the habit we practiced today — a theory this well-constructed, Farrell and Newman’s, is still worth testing against real cases, and real cases sometimes push back.</p>
<p>For where we’re headed: we’re back with Oatley next time, but keep today in mind, because a question has been building underneath this whole unit — the states that currently write the rules of this system are not guaranteed to be the only ones with real leverage left to use, and what happens as that changes is still being worked out, including by scholars like the ones you read today.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="iu-trident.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>INTL 503 | Economic Coercion and Economic Statecraft</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.15,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp("https:\/\/Sarah-BD\.github\.io\/intl503\/");
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>